/**
 * Gitai Earthmovers — Branded PDF Report Engine
 */
const PdfEngine = (function () {
  const BRAND = {
    company: 'Gitai Earthmovers',
    tagline: 'Audit & Partner Settlement System',
    accent: [245, 197, 24]
  };

  function addHeader(doc, title, generatedBy) {
    doc.setFillColor(...BRAND.accent);
    doc.rect(0, 0, 210, 28, 'F');
    doc.setTextColor(26, 29, 33);
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text(BRAND.company, 14, 14);
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(BRAND.tagline, 14, 21);

    doc.setTextColor(60, 60, 60);
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text(title, 14, 38);
    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.text('Generated: ' + formatDateTime(new Date().toISOString()), 14, 45);
    doc.text('Generated By: ' + (generatedBy || AuthModule.getUser()?.Name || 'System'), 14, 51);
    return 58;
  }

  function addFooter(doc, pageNum, totalPages) {
    const h = doc.internal.pageSize.height;
    doc.setDrawColor(...BRAND.accent);
    doc.line(14, h - 20, 196, h - 20);
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    doc.text(BRAND.company + ' — Confidential', 14, h - 12);
    doc.text('Page ' + pageNum + ' of ' + totalPages, 180, h - 12);
    doc.setFontSize(7);
    doc.text('Digital Signature: _________________________', 14, h - 6);
  }

  function generate(title, sections, filename) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const user = AuthModule.getUser()?.Name || 'System';
    let startY = addHeader(doc, title, user);

    sections.forEach((section, idx) => {
      if (idx > 0 && startY > 240) {
        doc.addPage();
        startY = 20;
      }

      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      doc.setTextColor(26, 29, 33);
      doc.text(section.heading, 14, startY);
      startY += 6;

      if (section.text) {
        doc.setFontSize(9);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(80, 80, 80);
        const lines = doc.splitTextToSize(section.text, 180);
        doc.text(lines, 14, startY);
        startY += lines.length * 5 + 4;
      }

      if (section.table) {
        doc.autoTable({
          html: section.table,
          startY,
          theme: 'grid',
          headStyles: { fillColor: BRAND.accent, textColor: [26, 29, 33] },
          styles: { fontSize: 8, cellPadding: 2 },
          margin: { left: 14, right: 14 }
        });
        startY = doc.lastAutoTable.finalY + 10;
      }
    });

    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addFooter(doc, i, totalPages);
    }

    doc.save((filename || title).replace(/\s+/g, '_') + '.pdf');
    AuditTrailModule.logExport(title);
  }

  function fromElement(title, element, filename) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const user = AuthModule.getUser()?.Name || 'System';
    let startY = addHeader(doc, title, user);

    const tables = element.querySelectorAll('table');
    tables.forEach((table, idx) => {
      if (idx > 0) startY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 10 : startY;
      doc.autoTable({
        html: table,
        startY,
        theme: 'grid',
        headStyles: { fillColor: BRAND.accent, textColor: [26, 29, 33] },
        styles: { fontSize: 8 }
      });
    });

    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      addFooter(doc, i, totalPages);
    }

    doc.save((filename || title).replace(/\s+/g, '_') + '.pdf');
    AuditTrailModule.logExport(title);
  }

  return { generate, fromElement, addHeader, addFooter, BRAND };
})();
